### ISSUE TITLE
Failing to Build (PBA or sedutil) on Linux 2.6

### ISSUE THREAD

**Issue by dagoodma** [Drive-Trust-Alliance/sedutil#83]
I have been trying to build sedutil on CentOS 6.8, linux **2.6.32-573.22.1.el6.x86_64**. Does sedutil work on linux kernel version 2.6? I've also tried some newer versions of 2.6; both **2.6.32-642.3.1.el6.x86_64** and **2.6.32-642.1.1.el6.x86_64** also fail with the same errors.

Here's the output from running `make CONF=Release` in _LinuxPBA/_: [http://pastebin.com/raw/cg2EZYUq](http://pastebin.com/raw/cg2EZYUq). The first error I see is

> /usr/src/kernels/2.6.32-642.3.1.el6.x86_64/include/asm-generic/bitops/fls64.h:37:2: error: #error BITS_PER_LONG not 32 or 64

and then it seems to get more interesting from there on:

> /usr/src/kernels/2.6.32-642.3.1.el6.x86_64/include/linux/thread_info.h:26:4: error: ‘u32’ does not name a type

**Comment by r0m30** [comment]
This appears to be an issue with the NVMe support in the 2.6 kernel.  I'm no kernel expert but can you try a more recent kernel 4.4+ would be best.
